apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../common/v1/dev/bff
namePrefix: bff-
commonLabels:
  microservice: bff
configMapGenerator:
  - name: app-config
    behavior: merge
    files:
      - application.yaml
# patchesStrategicMerge:
# - env-patch.yaml #형상 작성 원칙에 따라 환경변수에 api 주소를 넣을수도 있다. application-dev.yaml 의 주석 참조.
images:
  - name: asf-registry.cloudzcp.io/awesome-test/awesome-service
    newName: asf-registry.cloudzcp.io/awesome-test/awesome-bff-service
    newTag: 0.1.0