apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- redis.yaml
- quote.yaml
- web.yaml
vars:
- name: QUOTE_APP_URL
  objref:
    apiVersion: v1
    kind: Service
    name: quote-app-service
  fieldref:
    fieldpath: metadata.name
- name: QUOTE_APP_PORT
  objref:
    apiVersion: v1
    kind: Service
    name: quote-app-service
  fieldref:
    fieldpath: spec.ports.0.port
- name: REDIS_HOST
  objref:
    apiVersion: v1
    kind: Service
    name: redis
  fieldref:
    fieldpath: metadata.name
- name: REDIS_PORT
  objref:
    apiVersion: v1
    kind: Service
    name: redis
  fieldref:
    fieldpath: spec.ports.0.port
configMapGenerator:
  - name: quote-app-config
    files:
      - application.properties