---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: app-container
        image: cloudsvcdev/render-api-html
        ports:
        - containerPort: 80
        env:
        - name: API
          value: http://$(QUOTE_APP_URL):$(QUOTE_APP_PORT)/qod
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: web
  type: LoadBalancer