# common properties like db access information
# should be paired with ./backend-cred-patch.yaml
spring:
  # profiles:
  #   include: overlay
  # 위와같이 하고 마이크로서비스 오버레이에서 application-overlay.yaml을 configMap에 포함시키면
  # TA는 개발자들에게 규칙을 강제하는 셈이 되며, TA가 구성한 설정보다 application-overlay.yaml 이 
  # 더 높은 우선순위를 가지게 된다.
  # application.yaml 은 application-dev.yaml 보다
  # 우선순위가 낮으므로 마이크로서비스 오버레이에서 application.yaml 형식으로 설정을 만들면
  # TA 설정(application-dev.yaml)에 의해 덮어씌워지게 된다.
  redis:
    port: 6379
    host: 169.56.171.68
    password: ${REDIS_PASSWORD}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
        max-wait: 30
  datasource:
    platform: mariadb
    url: jdbc:mariadb://169.56.162.104:3306/instructor
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  cache:
    type: redis
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      save-mode: always
  rabbitmq:
    host: 169.56.171.66
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
  sleuth:
    traceId128: true
  sampler:
      probability: 1.0
  zipkin:
      baseUrl: http://zipkin.msa-framework:9411
management:
  health:
    rabbit:
      enabled: false
  endpoint:
    restart:
      enabled: true
logging:
    pattern:
        level: "%X{traceId} %X{spanId} %5p"