apiVersion: v1
kind: Namespace
metadata:
  annotations:
    app.skcc-quote.io/url: quote-app-service-dev
  labels:
    project: show-quote
    tier: dev
  name: quote-dev
---
apiVersion: v1
data:
  application-dev.properties: |-
    spring.cache.type=redis
    spring.redis.port=${REDIS_PORT}
    spring.redis.host=${REDIS_HOST}
    quote.api=http://quotes.rest/qod.json
  application.properties: |-
    spring.cache.type=redis
    spring.redis.port=6379
    spring.redis.host=localhost
    quote.api=http://quotes.rest/qod.json
kind: ConfigMap
metadata:
  annotations:
    app.skcc-quote.io/url: quote-app-service-dev
  labels:
    project: show-quote
    tier: dev
  name: quote-app-config-dev-5c25k97bbh
  namespace: quote-dev
---
apiVersion: v1
data:
  new-index.ejs: |-
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=600, initial-scale=1.0">
        <title>DEV-API</title>
    </head>
    <body>
        <h1>DEV Server Testing</h1>
        <p><%= data %></p>
    </body>
    </html>
kind: ConfigMap
metadata:
  annotations:
    app.skcc-quote.io/url: quote-app-service-dev
  labels:
    project: show-quote
    tier: dev
  name: web-config-dev-9g62k48669
  namespace: quote-dev
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.skcc-quote.io/url: quote-app-service-dev
  labels:
    project: show-quote
    tier: dev
  name: quote-app-service-dev
  namespace: quote-dev
spec:
  ports:
  - name: http
    port: 38080
    targetPort: 8080
  selector:
    app: quote-app
    project: show-quote
    tier: dev
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.skcc-quote.io/url: quote-app-service-dev
  labels:
    app: redis
    project: show-quote
    tier: dev
  name: redis-dev
  namespace: quote-dev
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    project: show-quote
    tier: dev
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.skcc-quote.io/url: quote-app-service-dev
  labels:
    app: web
    project: show-quote
    tier: dev
  name: web-dev
  namespace: quote-dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: web
    project: show-quote
    tier: dev
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.skcc-quote.io/url: quote-app-service-dev
  labels:
    project: show-quote
    tier: dev
  name: quote-app-dev
  namespace: quote-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-app
      project: show-quote
      tier: dev
  template:
    metadata:
      annotations:
        app.skcc-quote.io/url: quote-app-service-dev
      labels:
        app: quote-app
        project: show-quote
        tier: dev
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: redis-dev
        - name: REDIS_PORT
          value: "6379"
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        image: cloudsvcdev/quote-spring-app
        imagePullPolicy: IfNotPresent
        name: app-container
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /config
          name: app-config-volume
          readOnly: true
      volumes:
      - configMap:
          name: quote-app-config-dev-5c25k97bbh
        name: app-config-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.skcc-quote.io/url: quote-app-service-dev
  labels:
    app: redis
    project: show-quote
    tier: dev
  name: redis-dev
  namespace: quote-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      project: show-quote
      tier: dev
  template:
    metadata:
      annotations:
        app.skcc-quote.io/url: quote-app-service-dev
      labels:
        app: redis
        project: show-quote
        tier: dev
    spec:
      containers:
      - image: redis
        name: app-container
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.skcc-quote.io/url: quote-app-service-dev
  labels:
    project: show-quote
    tier: dev
  name: web-dev
  namespace: quote-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      project: show-quote
      tier: dev
  template:
    metadata:
      annotations:
        app.skcc-quote.io/url: quote-app-service-dev
      labels:
        app: web
        project: show-quote
        tier: dev
    spec:
      containers:
      - env:
        - name: PAGE
          valueFrom:
            configMapKeyRef:
              key: new-index.ejs
              name: web-config-dev-9g62k48669
        - name: API
          value: http://quote-app-service-dev:38080/qod
        image: cloudsvcdev/render-api-html:latest
        name: app-container
        ports:
        - containerPort: 80
