apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app
  labels:
    microservice: order
spec:
  selector:
    matchLabels:
      microservice: order
  template:
    metadata:
      labels:
        microservice: order
    spec:
      containers:
      - name: order-app
        image: asf-registry.cloudzcp.io/awesome-test/awesome-order-service:0.1.0
        volumeMounts:
        - mountPath: /config
          name: app-config-volume
      volumes:
      - name: app-config-volume
        configMap:
          name: order-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: order-app
  labels:
    microservice: order
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    microservice: order