apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-app
  labels:
    microservice: payment
spec:
  selector:
    matchLabels:
      microservice: payment
  template:
    metadata:
      labels:
        microservice: payment
    spec:
      containers:
      - name: payment-app
        image: asf-registry.cloudzcp.io/awesome-test/awesome-payment-service:0.1.0
        volumeMounts:
        - mountPath: /config
          name: app-config-volume
      volumes:
      - name: app-config-volume
        configMap:
          name: payment-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: payment-app
  labels:
    microservice: payment
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    microservice: payment