apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../base/v1
  - role.yaml
  - sa.yaml
commonLabels:
  cluster-tier: dev
nameSuffix: -v1-dev
configMapGenerator:
  - name: app-config
    behavior: merge
    files:
      - application-dev.yaml # TA 설정이 개발자보다 우선순위를 갖게 하기 위한 파일명 선정
patchesStrategicMerge:
  - backend-cred-patch.yaml
  - active-profile-patch.yaml
  - metric-patch.yaml
  - probe-patch.yaml
  - serviceport-patch.yaml
  - spec-patch.yaml