apiVersion: apps/v1
kind: Deployment
metadata:
  name: app  # base와 동일하게 명시해서 patch시 어떤 deployment에 대한 수정인지 kustomize가 인식
spec:
  template:
    metadata:
      annotations:
        # Metric
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/actuator/prometheus'
        prometheus.io/port: '8091'