apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  user: YWRtaW4=
  password: cW94U1ZJSkE4cQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  user: dXNlcg==
  password: ZUs4YUhvS1hYUQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  password: T0lwano4U09KUw==