apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-app
spec:
  template:
    spec:
      containers:
      - name: app-container
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev