apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-app
spec:
  template:
    spec:
      containers:
        - name: app-container
          readinessProbe:
            httpGet:
              path: /qod/reactive
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /qod/reactive
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 5