apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
      - name: app-container
        resources:
          limits:
            cpu: 500m
            memory: 512Mi