apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
bases:
  - ../../../deploy-config/base
  - ../../../deploy-config/pattern/config/dev
namePrefix: bff-
nameSuffix: -v0-dev
commonLabels:
  biz: bff-app
  app: awesome-shopping
images:
  - name: cloudsvcdev/microservice
    newName: asf-registry.cloudzcp.io/awesome-test/awesome-bff-service
    newTag: 0.1.0
configMapGenerator:
- name: app-config
  behavior: merge
  files:
    - application-overlay.yaml
# 패치 대상 파일 목록
patchesStrategicMerge:
  - replicas-patch.yaml
  - probe-patch.yaml
  # - serviceport-patch.yaml
  - spec-patch.yaml
  - metric-patch.yaml
patchesJson6902:
- target:
    version: v1
    kind: Service
    name: app
  path: service-patch.yaml
